name: devdockerqt5
services:
  # Pre run setup container
  init-setup:
    image: ${QTCREATOR_IMAGE_NAME:-zanyxdev/qt6-19-21-36-27.2.12479018}
    dns:
      - 8.8.8.8
      - 1.1.1.1
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 2G
    user: "root:root"
    dns:
        - 8.8.8.8
        - 8.8.4.4
    dns_search:
        - .
    build:                
      dockerfile: ./Dockerfile 
      args:   
        QT_VERSION: ${QT_VERSION}
        LANG: "ru-RU.UTF-8"
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        TZ: "Europe/Moscow"       
    environment:
      - QT_VERSION=${QT_VERSION}
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
      - LANG=ru-RU.UTF-8
      - QTCREATOR_URL=${QTCREATOR_URL}  
      - CCACHE_DIR=/ccache
      - CCACHE_TEMPDIR=/ccache/tmp
      #- TMPDIR=/tmp/build
      - CCACHE_DIRECT=true
      - CCACHE_INODECACHE=true
      - CCACHE_COMPILERCHECK=content
    volumes:
      - ${PWD}/init_2.sh:/root/init.sh 
      - src-volume:/usr/local/src
      - opt-volume:/opt
      - ccache-volume:/ccache
      #- type: tmpfs
      #  target: /tmp/build
      #  tmpfs:
      #    size: 4G  # Size in bytes (e.g., ~4GB)
    entrypoint: [] 
    command: ["sh", "-c", "chmod +x /root/init.sh; echo /root/init.sh"]       
    restart: "no"     
      
# Main dev container
  qtcreator:   
    image: ${QTCREATOR_IMAGE_NAME:-zanyxdev/qt6-19-21-36-27.2.12479018} 
    # Отключение ограничения ptrace
    security_opt:
      - seccomp:unconfined
    # Часто ptrace требует и повышенных привилегий
    # cap_add:
    #   - SYS_PTRACE
    # cap_add:
    #   - CAP_SYS_PTRACE
    cap_add:
      - SYS_PTRACE
      - CAP_SYS_PTRACE
    deploy:
      resources:
        limits:
          cpus: '2.50'
          memory: 4G
        reservations:
          cpus: '2.0'
    dns:
      - 8.8.8.8
      - 1.1.1.1   
    deploy:
      resources:
        limits:
          cpus: '1.75'
          memory: 6G
        reservations:
          cpus: '0.75'
          memory: 2G
    group_add:
      - ${GROUP_ID}
    depends_on:
      init-setup:
        condition: service_completed_successfully   
    dns:
        - 8.8.8.8
        - 8.8.4.4
    dns_search:
        - .
    build:                
      dockerfile: ./Dockerfile 
      args:   
        QT_VERSION: ${QT_VERSION}
        LANG: "ru-RU.UTF-8"
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        TZ: "Europe/Moscow"
    container_name: qtcreator-6.11-dev
    ports:
      - "4096:4096"
    environment:
      - TERM=xterm-256color
      - XDG_RUNTIME_DIR=/tmp/runtime-developer
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      - PULSE_COOKIE=/tmp/pulseaudio.cookie    
      - ANDROID_ADB_SERVER_ADDRESS=host.docker.internal
      - ADB_SERVER_SOCKET=tcp:host.docker.internal:5037
      - ANDROID_ADB_SERVER_PORT=5037 
      #- GPG_TTY=/dev/console
      #- GPG_TTY=$(tty)
      - CCACHE_DIR=/ccache/${USER_ID:-1000}
      - CCACHE_TEMPDIR=/ccache/${USER_ID:-1000}/tmp
      - DISPLAY=:0  # явно задаём, чтобы переопределить Dockerfile ENV
      - WORKSPACE_GID=1000  # Добавляем GID для workspace
      - WORKSPACE_UMASK=0002  # Маска прав для новых файлов
    devices:
      - /dev/dri:/dev/dri
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - ~/.config/pulse/cookie:/tmp/pulseaudio.cookie
      - /tmp/.X11-unix:/tmp/.X11-unix:ro  # явный проброс с ro-правами     
      - $XAUTH:/home/developer/.Xauthority
      - ccache-volume:/ccache      
      - src-volume:/usr/local/src
      - opt-volume:/opt
      - ${HOMEAPP}:/home/developer
      - share_workspace:/data/workspace
    stdin_open: true
    tty: true
    init: true  
    command: bash          

volumes:
  src-volume:
    name: ${SRC_VOLUME_NAME}
  opt-volume:
    name: ${OPT_VOLUME_NAME}
  ccache-volume:
    name: ${CCACHE_VOLUME}
  share_workspace:
    external: true
    name: share_workspace 
