name: devdockerqt5
services:
  # Pre run setup container
  init-setup:
    image: ${QTCREATOR_IMAGE_NAME:-zanyxdev/qt6-19-21-36-27.2.12479018}
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 4G
        reservations:
          cpus: '1.50'
          memory: 2G
    user: "root:root"
    build:                
      dockerfile: ./Dockerfile 
      args:   
        QT_VERSION: ${QT_VERSION}
        LANG: "ru-RU.UTF-8"
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        TZ: "Europe/Moscow"       
    environment:
      - QT_VERSION=${QT_VERSION}
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
      - LANG=ru-RU.UTF-8
      - QTCREATOR_URL=${QTCREATOR_URL}  
      - CCACHE_DIR=/ccache
      - CCACHE_TEMPDIR=/ccache/tmp
    volumes:
      - ${PWD}/init.sh:/root/init.sh 
      - src-volume:/usr/local/src
      - opt-volume:/opt
      - ccache-volume:/ccache
      - test-volume:/data
    entrypoint: [] 
    command: ["sh", "-c", "chmod +x /root/init.sh; echo /root/init.sh"]       
    restart: "no"     
      
  # Main dev container
  qtcreator:   
    image: ${QTCREATOR_IMAGE_NAME:-zanyxdev/qt6-19-21-36-27.2.12479018} 
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 6G
        reservations:
          cpus: '1.50'
          memory: 2G
    group_add:
      - ${GROUP_ID}
    depends_on:
      init-setup:
        condition: service_completed_successfully   
    build:                
      dockerfile: ./Dockerfile 
      args:   
        QT_VERSION: ${QT_VERSION}
        LANG: "ru-RU.UTF-8"
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        TZ: "Europe/Moscow"
    container_name: qtcreator-6.11-dev
    environment:
      - TERM=xterm-256color
      - XDG_RUNTIME_DIR=/tmp/runtime-developer1
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      - PULSE_COOKIE=/tmp/pulseaudio.cookie    
      - ANDROID_ADB_SERVER_ADDRESS=host.docker.internal
      - ADB_SERVER_SOCKET=tcp:host.docker.internal:5037
      - ANDROID_ADB_SERVER_PORT=5037 
      - GPG_TTY=/dev/console
      - CCACHE_DIR=/ccache/${USER_ID:-1000}
      - CCACHE_TEMPDIR=/ccache/${USER_ID:-1000}/tmp
      - DISPLAY=:0  # явно задаём, чтобы переопределить Dockerfile ENV
    devices:
      - /dev/dri:/dev/dri
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - ~/.config/pulse/cookie:/tmp/pulseaudio.cookie
      - /tmp/.X11-unix:/tmp/.X11-unix:ro  # явный проброс с ro-правами     
      - $XAUTH:/home/developer/.Xauthority
      - ccache-volume:/ccache      
      - src-volume:/usr/local/src
      - opt-volume:/opt
      - ${HOMEAPP}:/home/developer
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    init: true  
    command: bash          

volumes:
  src-volume:
    name: ${SRC_VOLUME_NAME}
  opt-volume:
    name: ${OPT_VOLUME_NAME}
  ccache-volume:
    name: ${CCACHE_VOLUME}
  test-volume:
    name: 6.11-opt-volume
